service: rciu

provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: eu-central-1
  memorySize: 128
  timeout: 30
  versionFunctions: false

custom:
  myStage: ${opt:stage, self:provider.stage}
  instrumentUpdatesContainerBucketName: ${opt:host-s3-bucket-name}
  nodeEnv:
    Fn::If: [IsProductionStage, 'production', 'development']

functions:
  instrumentUpdatesGenerator:
    handler: instrument-updates-generator.Handler
    description: Random Capital instrument updates generator.
    environment:
      NODE_ENV: ${self:custom.nodeEnv}
      HOST_S3_BUCKET_NAME: ${self:custom.instrumentUpdatesContainerBucketName}
    events:
      - schedule: rate(7 days)

resources:
  Conditions:
    IsProductionStage:
      Fn::Equals:
        - ${self:custom.myStage}
        - 'production'
  Resources:
    InstrumentUpdatesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.instrumentUpdatesContainerBucketName}
        VersioningConfiguration:
          Status: 'Enabled'
        WebsiteConfiguration:
          IndexDocument: 'instrument-updates.html'
          ErrorDocument: 'instrument-updates.html'
    InstrumentUpdatesBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: InstrumentUpdatesBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action: 's3:GetObject'
              Resource:
                Fn::Join:
                  - ''
                  -
                    - 'arn:aws:s3:::'
                    - Ref: InstrumentUpdatesBucket
                    - '/instrument-updates.html'
              Principal: '*'
            - Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:PutObject'
                - 's3:ListBucket'
              Resource:
                - Fn::Join:
                  - ''
                  -
                    - 'arn:aws:s3:::'
                    - Ref: InstrumentUpdatesBucket
                - Fn::Join:
                  - ''
                  -
                    - 'arn:aws:s3:::'
                    - Ref: InstrumentUpdatesBucket
                    - '/*'
              Principal:
                AWS:
                  - Fn::GetAtt: [IamRoleLambdaExecution, Arn]
